### ISSUE TITLE
BUG:演示网页显示问题

### ISSUE THREAD

**Issue by fuzi1996** [molian-Z/OmniMagicCube#2]
演示网页 [http://demo.mlyt.top/](http://demo.mlyt.top/) 显示问题

![image](https://github.com/molian-Z/OmniMagicCube/assets/21113919/f7930129-23e1-4155-83fa-15f59ec0b915)

css资源加载问题: 
![image](https://github.com/molian-Z/OmniMagicCube/assets/21113919/45dbfac4-46f9-4f1b-85db-9a74885d69a7)

**Comment by molian-Z** [comment]
快走

**Comment by molian-Z** [comment]
可能是存在缓存，尝试清空一下缓存

**Comment by molian-Z** [comment]
https://coow.gitee.io/omnimagiccube
再或者尝试这个网站是否存在问题

**Comment by fuzi1996** [comment]
> https://coow.gitee.io/omnimagiccube 再或者尝试这个网站是否存在问题

应该是缓存问题，这个网站没问题
